### ISSUE TITLE
Cart Validation

### ISSUE THREAD

**Issue by seb86** [seb86/WooCommerce-Cart-REST-API#1]
I would suggest working on this after all endpoints have been created and work well to handle the data for all product types and meta data.

**Comment by leeseawuyhs** [comment]
I have been a plugin for WooCommerce-Cart-REST-API. If you like plugin i can upload to review.

**Comment by Megan18** [comment]
Please upload, I am very stuck on this

**Comment by seb86** [comment]
Please dont comment unrlated to the issue. Thank you.

**Comment by Megan18** [comment]
Sorry, but is any development begin?

**Comment by seb86** [comment]
@Megan18 Yes but I have yet uploaded my progress so far. Currently busy working on my new site before I share any new content.

**Comment by Megan18** [comment]
:(

**Comment by leeseawuyhs** [comment]
I have been uploaded plugin into https://github.com/leeseawuyhs/WooCommerce-Cart-REST-API
(The idea fork from https://github.com/seb86/WooCommerce-Cart-REST-API)

**Comment by Megan18** [comment]
Leeseawuyhs you are hero! xoxo
