### ISSUE TITLE
Facing 404 error when we triggered API call using REST API

### ISSUE THREAD

**Issue by ponmurugan123** [seb86/WooCommerce-Cart-REST-API#10]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of WooCommerce Cart REST-API on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. I have installed and activated this plugin.
2. By triggering the API call, facing 404 error.
3. Details below,
API URL : http://sample.dev.net/wc/v2/cart/clear
Method : GET
Error : 404 page not found

## Isolating the problem

- [ ] This bug happens with only WooCommerce Cart REST-API plugin active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
1. What version of WooCommerce are you using?
2. What library/language are you using to call the API?

**Comment by ponmurugan123** [comment]
Hi Sebastien,
     Thanks for your quick reply....
Please find the details below,
1. Woo Commerce Version 3.1.2 
2. I have triggered that API call by using angular 5

**Comment by seb86** [comment]
Do you have WordPress v4.4 or above?
Do you have pretty permalinks in "**Settings > Permalinks**" so that the custom endpoints are supported. Default permalinks will not work.

**Comment by ponmurugan123** [comment]
I have used WordPress 4.8.5. 
Yes I have set pretty permalinks in **settings >permalinks** . But still am facing error.

**Comment by seb86** [comment]
Are you able to view the endpoint directly in your browser?

**Comment by seb86** [comment]
I just checked your URL and noticed a mistake. You forgot to request the REST API correctly.

Wrong Way: http://sample.dev.net/wc/v2/cart/clear

Correct Way: http://sample.dev.net/wp-json/wc/v2/cart/clear

**Comment by ponmurugan123** [comment]
Its working fine by loading this [http://sample.dev.net/wp-json/wc/v2/cart/clear]
Thanks!
