### ISSUE TITLE
Is it possible to get any customer's shopping cart by a customer ID?

### ISSUE THREAD

**Issue by notmmao** [seb86/WooCommerce-Cart-REST-API#11]
The situation is:
I have a woocommerence as backend and a python-flask middleware as frontend.
The frontend has built-in a key/secret pair associated a shop-manager-user.
The end-user sends a request to the frontend, the middleware authenticate the end-user and gets the resources from backend by the built-in key/secret pair. 
So I expect to find a way for endusers to access their own cart.
Thank You.

**Comment by seb86** [comment]
HI @notmmao 

When a customer has added items to the cart those items are stored in the database and a cookie on the users computer but to identify them by a customers ID im not sure.

I suggest looking at the cart class in the core of WooCommerce. This rest api is designed to do the same as the cart using its functions only. Nothing custom.

Let me know if a filter is required in the rest api somewhere once you have figured it out.

Thank you.

**Comment by notmmao** [comment]
Thank you for your reply and sorry to disturb your weekend.
> When a customer has added items to the cart those items are stored in the database and a cookie on the users computer but to identify them by a customers ID im not sure.
My middleware-frontend uses a different domain name than woocommerence-backend. so I can't get the cookie ISSUE by backend. but, I can get the the shop-manager-user(the woo-rest key/secret associated)'s cart item by WooCommerce-Cart-REST-API. So I think in the backend Database there should also be a data corresponding to the user local cookie.
> I suggest looking at the cart class in the core of WooCommerce. 
Review PHP code is so hard for me, I will try.
Thanks again.

**Comment by an-rahulpandey** [comment]
I am also trying to do the same, have you figured it out?

**Comment by FawadNL** [comment]
Having same issue here

**Comment by hudsoncliff** [comment]
I have been through the same.
I changed the way to send my requests for the cart API.
1. Generate a consumer secret and key by admin or  core function for customer
2. Send the cart API with the consumer key and secret as a parameter
this way the server knows which user requested the cart API.

**Comment by FawadNL** [comment]
Hi @hudsoncliff , thanks for that but that means we have to create a wc api key for every customer right?
