### ISSUE TITLE
rest_no_route response came when we removing the cart item

### ISSUE THREAD

**Issue by ponmurugan123** [seb86/WooCommerce-Cart-REST-API#14]
## Steps to reproduce the issue
![removing cart item using delete method](https://user-images.githubusercontent.com/35921785/36716092-109cd306-1bbf-11e8-8511-01563140fa39.png)
![rest_no_route response](https://user-images.githubusercontent.com/35921785/36716094-10d36880-1bbf-11e8-8ebe-2be81328f049.png)
![cart response](https://user-images.githubusercontent.com/35921785/36716118-21a84fcc-1bbf-11e8-98a1-6bea711b713b.png)

1. It is working fine when we retrieved the cart contents from '/wp-json/wc/v2/cart" call

2. But I have got rest_no_route response when I am trying to remove the cart item by using "/wp-json/wc/v2/cart?cart_item_key=<cart_item_key>" (used DELETE method)

3. Please refer **SS**

**Comment by seb86** [comment]
Thank you for reporting the issue. I will take a look at what went wrong and push a fix soon.

**Comment by seb86** [comment]
Please test the latest changes applied to the repository. The endpoint has changed to prevent conflict. I have also improved validation.

It is now: `/wp-json/wc/v2/cart/cart-item?cart_item_key=<cart_item_key>`

Let me know if you have any further issues with this.

Thank you.

**Comment by ponmurugan123** [comment]
Hi Sébastien,
Now able to trigger an API call with   "/wp-json/wc/v2/cart/cart-item?cart_item_key=<cart_item_key"

But now I am facing  **Unable to remove item from cart.** error from the API. Because I have sent the param as below

> cart_item_key:5ea1649a31336092c05438df996a3e59

In remove_item method, we are changing this param's type to integer by absint() method
Seems this might be the cause for this issue. Please check and confirm.

Thanks.

**Comment by ponmurugan123** [comment]
While triggering update API, following error came by response,
API : "/wp-json/wc/v2/cart/cart-item?cart_item_key=<cart_item_key"
Method : POST
<br />
<b>Warning</b>:  is_numeric() expects exactly 1 parameter, 3 given in <b>/opt/lampp/htdocs/sample.dev.net/wp-includes/rest-api/class-wp-rest-request.php</b> on line <b>903</b><br />
<br />
**<b>Fatal error</b>:  Uncaught Error: Call to a member function get_price() on null in /opt/lampp/htdocs/sample.dev.net/wp-content/plugins/woocommerce/includes/class-wc-cart.php:1157
Stack trace:**
#0 /opt/lampp/htdocs/sample.dev.net/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1093): WC_Cart-&gt;calculate_totals()
#1 /opt/lampp/htdocs/sample.dev.net/wp-content/plugins/WooCommerce-Cart-REST-API-master/includes/api/class-wc-rest-cart-controller.php(413): WC_Cart-&gt;set_quantity('5ea1649a3133609...', 3)
#2 /opt/lampp/htdocs/sample.dev.net/wp-includes/rest-api/class-wp-rest-server.php(947): WC_REST_Cart_Controller-&gt;update_item(Object(WP_REST_Request))
#3 /opt/lampp/htdocs/sample.dev.net/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))
#4 /opt/lampp/htdocs/sample.dev.net/wp-includes/rest-api.php(271): WP_REST_Server-&gt;serve_request('/wc/v2/cart/car...')
#5 /opt/lampp/htdocs/sample.dev.net/wp-includes/class-wp-hook.php(298): rest_api_loaded(Object(WP))
#6 /opt/lampp/htdocs/sampl in <b>/opt/lampp/htdocs/sample.dev.net/wp-content/plugins/woocommerce/includes/class-wc-cart.php</b> on line <b>1157</b><br />



When I debug this issue, found **$this->cart_contents** getting empty array .  Could you please suggest me about this?

**Comment by seb86** [comment]
Cart contents only returns empty if the cart is empty so you cant update an item that is not there.

Please share your WooCommerce system status report and tell me what library you are using with the rest api.

Thank you.

**Comment by ponmurugan123** [comment]
Hi Please find my site's  WooCommerce system status report

``
### WordPress Environment ###

Home URL: http://sample.dev.net
Site URL: http://sample.dev.net
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.26 (Unix) OpenSSL/1.0.2l PHP/7.1.7 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.1.7
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (23) ###

Cart REST API for WooCommerce: by Sébastien Dumont – 1.0.1
CMB2: by CMB2 team – 2.2.5.3
File Manager: by  – 4.1.6
Ionic2-Woo-Store: by  – 1.0
JSON API Auth: by Ali Qureshi – 1.8
JSON API: by Dan Phiffer – 1.1.1
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.9
Master Slider: by averta – 3.1.1
OptinMonster API: by OptinMonster Team – 1.2.1
WP REST API: by WP REST API Team – 2.0-beta15
Rewardsway: by  –
WC Cancel Order: by Vikram Singh – 2.5
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.4
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce Stock Manager: by Vladislav Musílek – 1.2.1
WooCommerce: by Automattic – 3.1.2 – 3.3.3 is available
WordPress Importer: by wordpressdotorg – 0.6.3
WP REST API Controller: by YIKES
Inc.
Evan Herman
yikesitskevin – 1.4.1

YITH WooCommerce Compare: by YITHEMES – 2.2.1
YITH WooCommerce Quick View: by YITHEMES – 1.2.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: #511 - /my-account/cart/
Checkout: #513 - /my-account/checkout/
My account: #509 - /my-account/account-details/

### Theme ###

Name: Alpha Store
Version: 1.4.0 – 1.4.1 is available
Author URL: http://themes4wp.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
``

wp--json/wc/v2/cart  call returns valid response which contains 2 products details in cart
But When I tried to update the cart item/remove the item from cart means It throws error (cart_contents got empty array).

Thank you

**Comment by seb86** [comment]
What library are you using I asked to get this error as I have not been able to replicate it.

**Comment by ponmurugan123** [comment]
Hi,
Sorry I did not get you clearly. Are you asking about front end libraries to make api request?

I am using angular 5 (ionic 3) with angular HTTP module.

**Comment by seb86** [comment]
I don’t know Angular sorry. I found this wrapper. https://github.com/michaeldoye/ng2woo

Let me know if that is helpful. Also, can you test with just WooCommerce and the Cart REST API enabled only.

Thanks.

**Comment by ponmurugan123** [comment]
Thanks for your link. I have verified it. That has basic code in angular.

I think,
From angular. It works well from making api request to WooCommerce. 

When I got cart details from v2/cart call, $this->cart_contents[key] has not updated .
So When we make update/remove call, we are getting cart items from $this->cart_contents variable only.

Could you please help me on why $this->cart_contents[key] is not updating ?

Thanks,

**Comment by seb86** [comment]
Could you share a code snippet please.

**Comment by ponmurugan123** [comment]
Please find the code to get cart from session


`
	/**
	 * Get the cart data from the PHP session and store it in class variables.
	 */
	public function get_cart_from_session() {
		// echo "cartcontents".json_encode($this->cart_session_data);
		// Load cart session data from session
		foreach ( $this->cart_session_data as $key => $default ) {
			$this->$key = WC()->session->get( $key, $default );
		}

		$update_cart_session         = false;
		$this->removed_cart_contents = array_filter( WC()->session->get( 'removed_cart_contents', array() ) );
		$this->applied_coupons       = array_filter( WC()->session->get( 'applied_coupons', array() ) );

		/**
		 * Load the cart object. This defaults to the persistent cart if null.
		 */
		$cart = WC()->session->get( 'cart', null );


		if ( is_null( $cart ) && ( $saved_cart = get_user_meta( get_current_user_id(), '_woocommerce_persistent_cart_' . get_current_blog_id(), true ) ) ) {
			$cart                = $saved_cart['cart'];
			// echo "cartcontents".json_encode($cart);
			$update_cart_session = true;
		} elseif ( is_null( $cart ) ) {
			$cart = array();
		}

		if ( is_array( $cart ) ) {
			// Prime meta cache to reduce future queries
			update_meta_cache( 'post', wp_list_pluck( $cart, 'product_id' ) );
			update_object_term_cache( wp_list_pluck( $cart, 'product_id' ), 'product' );

			foreach ( $cart as $key => $values ) {
				$product = wc_get_product( $values['variation_id'] ? $values['variation_id'] : $values['product_id'] );

				if ( ! empty( $product ) && $product->exists() && $values['quantity'] > 0 ) {

					if ( ! $product->is_purchasable() ) {

						// Flag to indicate the stored cart should be update
						$update_cart_session = true;
						/* translators: %s: product name */
						wc_add_notice( sprintf( __( '%s has been removed from your cart because it can no longer be purchased. Please contact us if you need assistance.', 'woocommerce' ), $product->get_name() ), 'error' );
						do_action( 'woocommerce_remove_cart_item_from_session', $key, $values );

					} else {

						// Put session data into array. Run through filter so other plugins can load their own session data
						$session_data = array_merge( $values, array( 'data' => $product ) );
						**$this->cart_contents[ $key ] = apply_filters( 'woocommerce_get_cart_item_from_session', $session_data, $values, $key );**

					}
				}
			}
		}`

**$this->cart_contents[ $key ] = apply_filters( 'woocommerce_get_cart_item_from_session', $session_data, $values, $key );**

This is the line I have mentioned earlier. When I searched globally to get **woocommerce_get_cart_item_from_session** , seems it is not available anywhere in my site code repo.

**Comment by seb86** [comment]
Sorry but I don't see how this is related to the API. I asked for the code snippet for how you are calling it. This is completely different.

**Comment by ponmurugan123** [comment]
Hi,
When I sent the REST API as below, issue has been working fine

`headers.append('Content-Type', 'application/json');
        var options = new RequestOptions({
            headers: headers,
            withCredentials: true
        });`

Thanks for supporting me to fix this issue.
