### ISSUE TITLE
Invalid Argument Error for foreach()

### ISSUE THREAD

**Issue by Mr-AjayM** [seb86/WooCommerce-Cart-REST-API#19]
Hello, I have found the Issue When there call the get cart API. calling the rest with [/wc/v2/cart](url). 
Errors are in the file WooCommerce-Cart-REST-API-master\includes\api\class-wc-rest-cart-controller.php

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of WooCommerce Cart REST-API on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [X] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Download the latest plugin and activate in your setup.
2. Setup the WooCommerce Store and API Keys.
3. Call the get cart API by [wc/v2/cart](url).

## Expected/actual behavior

When I follow those steps, I see the error ***Warning: Invalid argument supplied for foreach() in D:\woocommerce-api\wp-content\plugins\WooCommerce-Cart-REST-API-master\includes\api\class-wc-rest-cart-controller.php on line 164***

And 

**Warning: Cannot modify header information - headers already sent by (output started at D:\woocommerce-api\wp-content\plugins\WooCommerce-Cart-REST-API-master\includes\api\class-wc-rest-cart-controller.php:164) in D:\woocommerce-api\wp-includes\rest-api\class-wp-rest-server.php on line 1248**

I was expecting to see...
"Cart is Empty!"

## Isolating the problem

- [x] This bug happens with only WooCommerce Cart REST-API plugin active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
Thank you for reporting the issue @Mr-AjayM 

I see that I should be returning the response [here](https://github.com/seb86/WooCommerce-Cart-REST-API/blob/master/includes/api/class-wc-rest-cart-controller.php#L159) if the cart is empty. I will correct this asap.

**Comment by seb86** [comment]
@Mr-AjayM Can you confirm that the error is now gone after making the change.

**Comment by Mr-AjayM** [comment]
@seb86 Error is resolved.
