### ISSUE TITLE
Test | Endpoint | Add to Cart

### ISSUE THREAD

**Issue by seb86** [seb86/WooCommerce-Cart-REST-API#4]

**Comment by Megan18** [comment]
How can I help with testing?

**Comment by seb86** [comment]
@Megan18 I have yet to write documentation but if you follow [WooCommerce REST API documentation](http://woocommerce.github.io/woocommerce-rest-api-docs/) you will have some idea how to test.

**Comment by seb86** [comment]
@Megan18 Just thought I let you know that I have completed the documentation for my API. https://seb86.github.io/WooCommerce-Cart-REST-API-Docs/
