### ISSUE TITLE
Add Featured Product Image URL to Cart Endpoint

### ISSUE THREAD

**Issue by seb86** [seb86/WooCommerce-Cart-REST-API#5]
Would it be practical for the featured product image URL to be added to the cart endpoint per product so you would not have to do another request to get it?

This is what the cart endpoint returns currently as default.

![Cart endpoint with a product in cart.](https://cldup.com/sjfk5chCXB.png)

The same returns when `WC()->cart->get_cart();` is called but if you were to use the cart endpoint to display the products in the cart you don't have the featured product image to display with.

So do think it would be ok to add this variable to each product in the cart or would it cause performance issues?

**Comment by IntelliJAbhishek** [comment]
Please add featured url . Adding an extra field does not cause performance issue. Every cart show a image o product for that we need do an extra api call which make response time slow. so please add featured_image_url. #Request.

**Comment by seb86** [comment]
@IntelliJAbhishek Just the featured image in its full size, thumbnail or all WooCommerce image sizes?

**Comment by IntelliJAbhishek** [comment]
@seb86 Just the featured image in its full size thumbnail would be great.

**Comment by IntelliJAbhishek** [comment]
can you tell me how to use this API. I want to test it. As I m developing Mobile app for woo-commerce I'm looking forward to this API. Right now i'm using local storage but I want to use this api in my project. plox tell me how to configure this.

**Comment by IntelliJAbhishek** [comment]
Ok I added this plugin but when I add product I'm Getting Some wornings products adds successful but getting warnings in postman.
I have posted this ..
Method- POST
Endpoint- /cart/add
data- product_id=70 , quantity=2

**Response** 
```
<br />
<b>Warning</b>:  is_numeric() expects exactly 1 parameter, 3 given in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php</b> on line <b>858</b><br />
<br />
<b>Warning</b>:  is_numeric() expects exactly 1 parameter, 3 given in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php</b> on line <b>858</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php:858) in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1248</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php:858) in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api.php</b> on line <b>544</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php:858) in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api.php</b> on line <b>545</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php:858) in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api.php</b> on line <b>546</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api/class-wp-rest-request.php:858) in <b>/srv/users/serverpilot/apps/wordpress-plugins/public/wp-includes/rest-api.php</b> on line <b>547</b><br />
{"key":"7cbbc409ec990f19c78c75bd1e06f215","product_id":70,"variation_id":0,"variation":[],"quantity":4,"line_tax_data":{"subtotal":{"1":4.3636363636364},"total":{"1":4.3636363636364}},"line_subtotal":43.636363636364,"line_subtotal_tax":4.36,"line_total":43.636363636364,"line_tax":4.36,"data":{}}
```

**Comment by seb86** [comment]
@IntelliJAbhishek Please report issues or bugs related to the ticket. Also, I do not see anything related to those warnings with my API.
